# 01 - Thu thập dữ liệu đánh giá Laptop trên FPTShop
Notebook này crawl dữ liệu đánh giá từ FPTShop theo hướng HTTP thuần (requests), chuẩn hóa schema tương thích pipeline EDA và lưu CSV UTF-8.

In [8]:
%pip install requests pandas

Requirement already satisfied: requests in d:\codepython\ktlttrongptdl\.venv\lib\site-packages (2.33.1)
Requirement already satisfied: pandas in d:\codepython\ktlttrongptdl\.venv\lib\site-packages (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\codepython\ktlttrongptdl\.venv\lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in d:\codepython\ktlttrongptdl\.venv\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in d:\codepython\ktlttrongptdl\.venv\lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in d:\codepython\ktlttrongptdl\.venv\lib\site-packages (from requests) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in d:\codepython\ktlttrongptdl\.venv\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\codepython\ktlttrongptdl\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\codepython\ktlttrongptdl\.venv\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in d:\codepython\ktlttrongptdl\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import json
import re
import time
from html import unescape
from urllib.parse import urljoin, urlparse, parse_qsl, urlencode
import hashlib

import pandas as pd
import requests

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8",
    "Referer": "https://fptshop.com.vn/"
}

SESSION = requests.Session()
SESSION.headers.update(HEADERS)

COMMENT_API_URL = "https://papi.fptshop.com.vn/gw/v1/public/bff-before-order/comment/list"
COMMENT_API_HEADERS = {
    "Accept": "application/json",
    "Content-Type": "application/json",
    "Order-Channel": "1",
    "Referer": "https://fptshop.com.vn/",
}


def with_query_param(url: str, key: str, value):
    parsed = urlparse(url)
    query = dict(parse_qsl(parsed.query, keep_blank_values=True))
    query[key] = str(value)
    return parsed._replace(query=urlencode(query)).geturl()


def collect_product_urls(
    search_url: str,
    max_pages_safety: int = 300,
    max_products: int | None = None,
    hard_cap: int | None = None,
    consecutive_empty_pages: int = 3,
    delay_seconds: float = 0.8,
):
    product_urls = []
    seen = set()
    empty_pages = 0

    for page in range(1, max_pages_safety + 1):
        page_url = with_query_param(search_url, "page", page)
        response = SESSION.get(page_url, timeout=20)
        response.raise_for_status()
        html_text = response.text

        matches = []
        matches.extend(re.findall(r'<a[^>]+title="[^"]+"[^>]+href="(/may-tinh-xach-tay/[^"]+)"', html_text, flags=re.IGNORECASE))
        matches.extend(re.findall(r'href="(https://fptshop\.com\.vn/may-tinh-xach-tay/[^"]*\?sku=[^"]+|/may-tinh-xach-tay/[^"]*\?sku=[^"]+)"', html_text))
        new_count = 0

        for href in matches:
            full_url = urljoin("https://fptshop.com.vn", href.strip())
            if full_url in seen:
                continue
            seen.add(full_url)
            product_urls.append(full_url)
            new_count += 1

            if max_products is not None and len(product_urls) >= max_products:
                print(f"Đã đạt max_products={max_products}.")
                return product_urls
            if hard_cap is not None and len(product_urls) >= hard_cap:
                print(f"Đã đạt hard_cap={hard_cap} để dừng an toàn.")
                return product_urls

        print(f"Trang {page}: +{new_count} URL sản phẩm, tổng {len(product_urls)}")

        if new_count == 0:
            empty_pages += 1
        else:
            empty_pages = 0

        if empty_pages >= consecutive_empty_pages:
            print(f"Dừng do {consecutive_empty_pages} trang liên tiếp không có URL mới.")
            break

        time.sleep(delay_seconds)

    return product_urls


def extract_product_code(html_text: str):
    normalized = html_text.replace('\\"', '"').replace('\\/', '/')
    # Uu tien ma content id 12 chu so ma frontend dung khi goi comment API.
    match_content_id = re.search(r'"code":"([0-9]{12})","name":"[^"]+","displayName":"[^"]+"', normalized)
    if match_content_id:
        return match_content_id.group(1)

    match = re.search(r'"upc":\{"code":"([^"]+)"\}', normalized)
    if match:
        return match.group(1)

    match_alt = re.search(r'"sku"\s*:\s*"([0-9]{6,})"', normalized)
    if match_alt:
        return match_alt.group(1)

    return None


def _to_int(value):
    if value is None:
        return None
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return None


def _clean_text(value):
    if value is None:
        return None
    cleaned = unescape(str(value))
    cleaned = re.sub(r"<[^>]+>", " ", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned or None


def _extract_urls(value):
    if value is None:
        return []
    if isinstance(value, str):
        return [value.strip()] if value.strip() else []
    urls = []
    if isinstance(value, list):
        for item in value:
            if isinstance(item, str) and item.strip():
                urls.append(item.strip())
            elif isinstance(item, dict):
                for key in ("url", "image", "src", "thumb", "thumbnail"):
                    img = item.get(key)
                    if isinstance(img, str) and img.strip():
                        urls.append(img.strip())
                        break
    elif isinstance(value, dict):
        for key in ("url", "image", "src", "thumb", "thumbnail"):
            img = value.get(key)
            if isinstance(img, str) and img.strip():
                urls.append(img.strip())
                break
    return urls


def extract_product_metadata(html_text: str, item_code: str | None = None):
    metadata = {
        "item_id": item_code,
        "product_name": None,
        "brand": None,
        "price": None,
        "final_price": None,
        "rating_count_total": None,
        "image_product": None,
    }

    detail_match = re.search(r'<script[^>]*id="detail-product-script"[^>]*type="application/ld\+json"[^>]*>(.*?)</script>', html_text, flags=re.DOTALL | re.IGNORECASE)
    if detail_match:
        detail_raw = unescape(detail_match.group(1)).strip()
        try:
            detail_candidate = json.loads(detail_raw)
        except json.JSONDecodeError:
            detail_candidate = None
        if isinstance(detail_candidate, dict) and "Product" in ([detail_candidate.get("@type")] if not isinstance(detail_candidate.get("@type"), list) else detail_candidate.get("@type")):
            metadata["product_name"] = detail_candidate.get("name") or metadata["product_name"]
            detail_brand = detail_candidate.get("brand")
            if isinstance(detail_brand, dict):
                metadata["brand"] = detail_brand.get("name") or metadata["brand"]
            elif isinstance(detail_brand, str):
                metadata["brand"] = detail_brand or metadata["brand"]
            detail_offers = detail_candidate.get("offers")
            if isinstance(detail_offers, dict):
                metadata["price"] = metadata["price"] or _to_int(detail_offers.get("price"))
                metadata["final_price"] = metadata["final_price"] or _to_int(detail_offers.get("price"))
            detail_agg = detail_candidate.get("aggregateRating")
            if isinstance(detail_agg, dict):
                metadata["rating_count_total"] = metadata["rating_count_total"] or _to_int(detail_agg.get("reviewCount"))
            detail_image = _extract_urls(detail_candidate.get("image"))
            if detail_image:
                metadata["image_product"] = metadata["image_product"] or detail_image[0]

    ldjson_blocks = re.findall(
        r'<script[^>]*type="application/ld\\+json"[^>]*>(.*?)</script>',
        html_text,
        flags=re.DOTALL | re.IGNORECASE,
    )

    for block in ldjson_blocks:
        raw = unescape(block).strip()
        if not raw:
            continue
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError:
            continue

        candidates = parsed if isinstance(parsed, list) else [parsed]
        for candidate in candidates:
            if not isinstance(candidate, dict):
                continue
            candidate_type = candidate.get("@type")
            type_list = candidate_type if isinstance(candidate_type, list) else [candidate_type]
            if "Product" not in type_list:
                continue

            metadata["product_name"] = metadata["product_name"] or candidate.get("name")

            brand = candidate.get("brand")
            if isinstance(brand, dict):
                metadata["brand"] = metadata["brand"] or brand.get("name")
            elif isinstance(brand, str):
                metadata["brand"] = metadata["brand"] or brand

            offers = candidate.get("offers")
            if isinstance(offers, dict):
                metadata["price"] = metadata["price"] or _to_int(offers.get("price"))
            elif isinstance(offers, list):
                for offer in offers:
                    if isinstance(offer, dict) and offer.get("price") is not None:
                        metadata["price"] = metadata["price"] or _to_int(offer.get("price"))
                        break

            agg = candidate.get("aggregateRating")
            if isinstance(agg, dict):
                metadata["rating_count_total"] = metadata["rating_count_total"] or _to_int(agg.get("reviewCount"))

            image_urls = _extract_urls(candidate.get("image"))
            if image_urls and not metadata["image_product"]:
                metadata["image_product"] = image_urls[0]

    normalized = html_text.replace('\\"', '"').replace('\\/', '/')

    if not metadata["product_name"]:
        name_match = re.search(r'"upc":\{"code":"[^"]+","name":"([^"]+)"', normalized)
        if name_match:
            metadata["product_name"] = name_match.group(1)

    if not metadata["brand"]:
        brand_match = re.search(r'"brand":\{"code":"[^"]+","name":"([^"]+)"', normalized)
        if brand_match:
            metadata["brand"] = brand_match.group(1)

    if metadata["final_price"] is None:
        final_price_match = re.search(r'"productAdvanceInfo":\{.*?"finalPrice":(\d+)', normalized, flags=re.DOTALL)
        if final_price_match:
            metadata["final_price"] = _to_int(final_price_match.group(1))

    if metadata["price"] is None:
        price_match = re.search(r'"productAdvanceInfo":\{.*?"price":(\d+)', normalized, flags=re.DOTALL)
        if price_match:
            metadata["price"] = _to_int(price_match.group(1))

    if metadata["image_product"] is None:
        img_match = re.search(r'"primaryImage":\{"url":"([^"]+)"\}', normalized)
        if img_match:
            metadata["image_product"] = img_match.group(1)

    if metadata["final_price"] is None:
        metadata["final_price"] = metadata["price"]

    return metadata


def extract_comment_payload(html_text: str):
    normalized = html_text.replace('\\"', '"').replace('\\/', '/')

    pattern = r'"comment":(\{.*?"totalCount":\d+.*?\})\s*,\s*"policyProduct"'
    match = re.search(pattern, normalized, flags=re.DOTALL)
    if not match:
        return {}

    comment_raw = match.group(1)
    try:
        return json.loads(comment_raw)
    except json.JSONDecodeError:
        return {}


def fetch_comment_page(content_id: str, skip_count: int = 0, max_result_count: int = 6, state: list[str] | None = None):
    payload = {
        "content": {"id": str(content_id), "type": "PRODUCT"},
        "state": state or ["ACTIVE"],
        "skipCount": int(skip_count),
        "maxResultCount": int(max_result_count),
        "sortMethod": 1,
    }
    response = SESSION.post(
        COMMENT_API_URL,
        json=payload,
        headers=COMMENT_API_HEADERS,
        timeout=20,
    )
    response.raise_for_status()

    data = response.json()
    if not isinstance(data, dict):
        raise RuntimeError("Phản hồi API comment không đúng định dạng JSON đối tượng.")
    if data.get("status") != 200:
        message = data.get("error", {}).get("message") or data.get("message") or "Lấy comment thất bại."
        raise RuntimeError(message)

    comment_data = data.get("data") or {}
    items = comment_data.get("items") or []
    total_count = _to_int(comment_data.get("totalCount"))
    return items, total_count


def fetch_product_reviews(product_url: str, page_size: int = 6):
    response = SESSION.get(product_url, timeout=20)
    response.raise_for_status()
    html_text = response.text

    item_code = extract_product_code(html_text)
    product_meta = extract_product_metadata(html_text=html_text, item_code=item_code)

    review_items = []
    total_count = None

    if item_code:
        try:
            review_items, total_count = fetch_comment_page(content_id=item_code, skip_count=0, max_result_count=page_size)
        except Exception as exc:
            print(f"Không lấy được comment API cho {product_url}: {exc}")

    if not review_items:
        comment_payload = extract_comment_payload(html_text)
        review_items = comment_payload.get("items") or []
        total_count = total_count or _to_int(comment_payload.get("totalCount")) or len(review_items)

    if product_meta.get("rating_count_total") is None:
        product_meta["rating_count_total"] = _to_int(total_count or len(review_items))

    return product_meta, review_items, total_count, item_code


def parse_rating_row(rating_row: dict, product_meta: dict, product_url: str, row_index: int):
    created_raw = (
        rating_row.get("createdAt")
        or rating_row.get("createAt")
        or rating_row.get("createdDate")
        or rating_row.get("creationTime")
        or rating_row.get("created_time")
        or rating_row.get("time")
    )
    created_at = pd.to_datetime(created_raw, errors="coerce")
    created_at = created_at.isoformat() if pd.notna(created_at) else None

    user_id = (
        rating_row.get("userId")
        or rating_row.get("customerId")
        or rating_row.get("memberId")
        or rating_row.get("fullName")
        or "anonymous"
    )
    cmt_id = rating_row.get("id") or rating_row.get("commentId") or rating_row.get("_id")
    if cmt_id is None:
        fallback = f"{product_url}_{row_index}_{rating_row.get('content', '')}"
        cmt_id = hashlib.md5(fallback.encode("utf-8")).hexdigest()[:16]

    rating_star = rating_row.get("score") or rating_row.get("rating") or rating_row.get("star")
    comment = (
        rating_row.get("content")
        or rating_row.get("comment")
        or rating_row.get("commentContent")
        or ""
    )
    comment = _clean_text(comment) or ""
    review_title = (
        rating_row.get("title")
        or rating_row.get("subject")
        or rating_row.get("headline")
        or rating_row.get("reviewTitle")
        or None
    )

    verified_raw = (
        rating_row.get("verified_purchase")
        or rating_row.get("verifiedPurchase")
        or rating_row.get("isVerified")
        or rating_row.get("isPurchased")
        or rating_row.get("is_buyer")
    )
    verified_purchase = None
    if verified_raw is not None:
        if isinstance(verified_raw, bool):
            verified_purchase = verified_raw
        elif isinstance(verified_raw, (int, float)):
            verified_purchase = bool(verified_raw)
        elif isinstance(verified_raw, str):
            verified_purchase = verified_raw.strip().lower() in {"true", "1", "yes", "y", "co", "có"}

    product_items = (
        rating_row.get("variantName")
        or rating_row.get("modelName")
        or rating_row.get("attributeValue")
        or ""
    )

    reply_content = None
    reply_created_at = None
    reply_user_id = None
    reply_is_admin = None
    reply_like_count = None
    children = rating_row.get("children") or []
    if isinstance(children, list):
        first_reply = next((child for child in children if isinstance(child, dict)), None)
        if first_reply:
            reply_content = _clean_text(first_reply.get("content"))
            reply_raw = first_reply.get("creationTime") or first_reply.get("createdAt") or first_reply.get("createdDate")
            reply_dt = pd.to_datetime(reply_raw, errors="coerce")
            reply_created_at = reply_dt.isoformat() if pd.notna(reply_dt) else None
            reply_user_id = first_reply.get("fullName") or first_reply.get("userId") or first_reply.get("customerId")
            if first_reply.get("isAdministrator") is not None:
                reply_is_admin = bool(first_reply.get("isAdministrator"))
            reply_like_count = first_reply.get("like") or first_reply.get("helpful") or 0

    image_review_urls = []
    for key in ("images", "imageUrls", "image_urls", "attachments", "pictures", "photos", "media"):
        if key in rating_row:
            image_review_urls = _extract_urls(rating_row.get(key))
            if image_review_urls:
                break
    image_review = " | ".join(image_review_urls) if image_review_urls else None

    return {
        "review_id": f"{user_id}_{cmt_id}",
        "shop_id": "FPTShop",
        "item_id": product_meta.get("item_id"),
        "product_url": product_url,
        "product_name": product_meta.get("product_name"),
        "brand": product_meta.get("brand"),
        "price": product_meta.get("price"),
        "final_price": product_meta.get("final_price"),
        "rating_count_total": product_meta.get("rating_count_total"),
        "user_id": str(user_id),
        "rating_star": rating_star,
        "review_title": review_title,
        "comment": comment,
        "verified_purchase": verified_purchase,
        "image_product": product_meta.get("image_product"),
        "image_review": image_review,
        "created_at": created_at,
        "like_count": rating_row.get("like") or rating_row.get("helpful") or 0,
        "product_items": str(product_items).strip(),
        "reply_content": reply_content,
        "reply_created_at": reply_created_at,
        "reply_user_id": reply_user_id,
        "reply_is_admin": reply_is_admin,
        "reply_like_count": reply_like_count,
        "source": "FPTShop"
    }


def crawl_product_reviews(product_url: str, max_reviews: int | None = None, page_size: int = 6, delay_seconds: float = 1.2):
    product_meta, page_reviews, total_count, item_code = fetch_product_reviews(product_url=product_url, page_size=page_size)

    reviews = []
    seen_review_ids = set()
    skip_count = 0
    page_number = 1
    api_entities_seen = 0
    max_retry_empty_page = 1

    while True:
        if max_reviews is not None and len(reviews) >= max_reviews:
            break

        if not page_reviews:
            print(f"Trang {page_number}: không còn comment nào để thu thập.")
            break

        page_added = 0
        page_entities = 0
        for idx, row in enumerate(page_reviews):
            if max_reviews is not None and len(reviews) >= max_reviews:
                break

            children = row.get("children") or []
            child_count = sum(1 for child in children if isinstance(child, dict)) if isinstance(children, list) else 0
            page_entities += 1 + child_count

            parsed = parse_rating_row(row, product_meta=product_meta, product_url=product_url, row_index=skip_count + idx)
            if not parsed["comment"] and not parsed.get("reply_content"):
                continue
            if parsed["review_id"] in seen_review_ids:
                continue

            seen_review_ids.add(parsed["review_id"])
            reviews.append(parsed)
            page_added += 1

        api_entities_seen += page_entities

        total_label = total_count if total_count is not None else "?"
        print(f"Trang {page_number}: +{page_added} comment, tổng {len(reviews)}/{total_label}")

        if total_count is not None and len(reviews) >= total_count:
            break

        if len(page_reviews) < page_size:
            break

        next_skip = skip_count + len(page_reviews)
        page_number += 1

        if max_reviews is not None and len(reviews) >= max_reviews:
            break

        time.sleep(delay_seconds)
        try:
            next_page_reviews, page_total = fetch_comment_page(content_id=item_code, skip_count=next_skip, max_result_count=page_size)
            if total_count is None:
                total_count = page_total

            if not next_page_reviews and total_count is not None and next_skip < total_count:
                for retry_idx in range(max_retry_empty_page):
                    print(f"Trang {page_number}: API trả rỗng bất thường, thử lại lần {retry_idx + 1}/{max_retry_empty_page}.")
                    time.sleep(delay_seconds)
                    retry_page_reviews, _ = fetch_comment_page(content_id=item_code, skip_count=next_skip, max_result_count=page_size)
                    if retry_page_reviews:
                        next_page_reviews = retry_page_reviews
                        break

            skip_count = next_skip
            page_reviews = next_page_reviews
        except Exception as exc:
            print(f"Lỗi khi tải trang comment thứ {page_number}: {exc}")
            break

    print(f"{product_url} -> lấy {len(reviews)} comment hiển thị / totalCount={total_count}")
    if total_count is not None:
        if total_count > api_entities_seen:
            print("Lưu ý: có thể còn dữ liệu chưa lấy do API ẩn bớt bình luận theo trạng thái hiển thị hoặc thay đổi cơ chế phân trang.")
        elif total_count > len(reviews):
            print("Ghi chú: totalCount có thể bao gồm cả phản hồi con (children), nên số comment gốc thu được có thể thấp hơn totalCount.")

    return pd.DataFrame(reviews)

In [10]:
search_url = "https://fptshop.com.vn/tim-kiem?s=laptop&sort=noi-bat&categories=may-tinh-xach-tay"
product_urls = collect_product_urls(
    search_url=search_url,
    max_pages_safety=300,
    max_products=None,
    hard_cap=None,
    consecutive_empty_pages=3,
    delay_seconds=0.8
)

display(product_urls[:10])
print(f"Tổng URL sản phẩm laptop đã thu thập: {len(product_urls)}")

if not product_urls:
    raise ValueError("Không lấy được danh sách product_urls từ trang tìm kiếm FPTShop.")

Trang 1: +24 URL sản phẩm, tổng 24
Trang 2: +24 URL sản phẩm, tổng 48
Trang 3: +24 URL sản phẩm, tổng 72
Trang 4: +24 URL sản phẩm, tổng 96
Trang 5: +24 URL sản phẩm, tổng 120
Trang 6: +24 URL sản phẩm, tổng 144
Trang 7: +24 URL sản phẩm, tổng 168
Trang 8: +24 URL sản phẩm, tổng 192
Trang 9: +24 URL sản phẩm, tổng 216
Trang 10: +24 URL sản phẩm, tổng 240
Trang 11: +24 URL sản phẩm, tổng 264
Trang 12: +24 URL sản phẩm, tổng 288
Trang 13: +24 URL sản phẩm, tổng 312
Trang 14: +24 URL sản phẩm, tổng 336
Trang 15: +24 URL sản phẩm, tổng 360
Trang 16: +24 URL sản phẩm, tổng 384
Trang 17: +24 URL sản phẩm, tổng 408
Trang 18: +24 URL sản phẩm, tổng 432
Trang 19: +24 URL sản phẩm, tổng 456
Trang 20: +24 URL sản phẩm, tổng 480
Trang 21: +24 URL sản phẩm, tổng 504
Trang 22: +24 URL sản phẩm, tổng 528
Trang 23: +24 URL sản phẩm, tổng 552
Trang 24: +24 URL sản phẩm, tổng 576
Trang 25: +24 URL sản phẩm, tổng 600
Trang 26: +24 URL sản phẩm, tổng 624
Trang 27: +24 URL sản phẩm, tổng 648
Trang 28: +24 URL sản phẩm, tổng 672
Trang 29: +24 URL sản phẩm, tổng 696
Trang 30: +24 URL sản phẩm, tổng 720
Trang 31: +24 URL sản phẩm, tổng 744
Trang 32: +24 URL sản phẩm, tổng 768
Trang 33: +24 URL sản phẩm, tổng 792
Trang 34: +24 URL sản phẩm, tổng 816
Trang 35: +24 URL sản phẩm, tổng 840
Trang 36: +24 URL sản phẩm, tổng 864
Trang 37: +24 URL sản phẩm, tổng 888
Trang 38: +24 URL sản phẩm, tổng 912
Trang 39: +24 URL sản phẩm, tổng 936
Trang 40: +24 URL sản phẩm, tổng 960
Trang 41: +24 URL sản phẩm, tổng 984
Trang 42: +16 URL sản phẩm, tổng 1000
Trang 43: +0 URL sản phẩm, tổng 1000
Trang 44: +0 URL sản phẩm, tổng 1000
Trang 45: +0 URL sản phẩm, tổng 1000
Dừng do 3 trang liên tiếp không có URL mới.

['https://fptshop.com.vn/may-tinh-xach-tay/lenovo-thinkpad-x1-carbon-gen-13-u7-258v-21ns010jvn',
 'https://fptshop.com.vn/may-tinh-xach-tay/colorful-rimbook-l1-i5-13420h-a10205500050',
 'https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-14-m5-pro-2026-15cpu-16gpu-24gb-2tb',
 'https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-16-m5-max-2026-18cpu-40gpu-64gb-4tb-nano',
 'https://fptshop.com.vn/may-tinh-xach-tay/msi-stealth-16-ai-b3wg-008vn-u9-386h',
 'https://fptshop.com.vn/may-tinh-xach-tay/asus-zenbook-14-ux3405ca-st629w-ultra-7-255h',
 'https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-s16-m3607ha-sh186w-ryzen-7-260',
 'https://fptshop.com.vn/may-tinh-xach-tay/lenovo-gaming-loq-15irx10-i7-13645hx-83je01agvn',
 'https://fptshop.com.vn/may-tinh-xach-tay/macbook-air-13-m5-2026-10cpu-8gpu-16gb-512gb',
 'https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-14-m5-2026-10cpu-10gpu-32gb-2tb-nano-96w']

Tổng URL sản phẩm laptop đã thu thập: 1000

In [11]:
all_frames = []
total_urls = len(product_urls)

for idx, url in enumerate(product_urls, start=1):
    print(f"[{idx}/{total_urls}]")
    df_item = crawl_product_reviews(url, max_reviews=None, page_size=6, delay_seconds=1.2)
    if not df_item.empty:
        all_frames.append(df_item)

if not all_frames:
    raise RuntimeError("Không thu được dữ liệu. Kiểm tra lại URL hoặc thử chạy lại với mạng khác.")

df_raw = pd.concat(all_frames, ignore_index=True)
df_raw = df_raw.drop_duplicates(subset=["review_id"]).reset_index(drop=True)

display(df_raw.head())
display(df_raw.tail())
print(f"Tổng số review thu được: {len(df_raw)}")

[1/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-thinkpad-x1-carbon-gen-13-u7-258v-21ns010jvn -> lấy 0 comment hiển thị / totalCount=0
[2/1000]
Trang 1: +1 comment, tổng 1/1
https://fptshop.com.vn/may-tinh-xach-tay/colorful-rimbook-l1-i5-13420h-a10205500050 -> lấy 1 comment hiển thị / totalCount=1
[3/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-14-m5-pro-2026-15cpu-16gpu-24gb-2tb -> lấy 0 comment hiển thị / totalCount=0
[4/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-16-m5-max-2026-18cpu-40gpu-64gb-4tb-nano -> lấy 0 comment hiển thị / totalCount=0
[5/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/msi-stealth-16-ai-b3wg-008vn-u9-386h -> lấy 0 comment hiển thị / totalCount=0
[6/1000]
Trang 1: +1 comment, tổng 1/1
https://fptshop.com.vn/may-tinh-xach-tay/asus-zenbook-14-ux3405ca-st629w-ultra-7-255h -> lấy 1 comment hiển thị / totalCount=1
[7/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-s16-m3607ha-sh186w-ryzen-7-260 -> lấy 0 comment hiển thị / totalCount=0
[8/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-gaming-loq-15irx10-i7-13645hx-83je01agvn -> lấy 0 comment hiển thị / totalCount=0
[9/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-air-13-m5-2026-10cpu-8gpu-16gb-512gb -> lấy 0 comment hiển thị / totalCount=0
[10/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-14-m5-2026-10cpu-10gpu-32gb-2tb-nano-96w -> lấy 0 comment hiển thị / totalCount=0
[11/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-s14-m3407ga-sf030w-ryzen-ai-7-445 -> lấy 0 comment hiển thị / totalCount=0
[12/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-air-13-m5-2026-10cpu-10gpu-24gb-1tb -> lấy 0 comment hiển thị / totalCount=0
[13/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-16-m5-pro-2026-18cpu-20gpu-24gb-1tb-nano -> lấy 0 comment hiển thị / totalCount=0
[14/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-s14-s3407ca-sf913w-ultra-5-225h -> lấy 0 comment hiển thị / totalCount=0
[15/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-gaming-loq-15arp10e-ryzen-7-170-83s000dcvn -> lấy 0 comment hiển thị / totalCount=0
[16/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-s14-s3407qa-sf043w-qualcomm-x1-26-100 -> lấy 0 comment hiển thị / totalCount=0
[17/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-thinkbook-14-g9-irl-core-7-240h-21uy0092vn -> lấy 0 comment hiển thị / totalCount=0
[18/1000]
Trang 1: +1 comment, tổng 1/1
https://fptshop.com.vn/may-tinh-xach-tay/macbook-air-15-m5-2026-10cpu-10gpu-24gb-1tb -> lấy 1 comment hiển thị / totalCount=1
[19/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-zenbook-14-ux3405ca-st628w-ultra-5-225h -> lấy 0 comment hiển thị / totalCount=0
[20/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-thinkbook-16-g9-irl-i5-13420h-21us008fvn -> lấy 0 comment hiển thị / totalCount=0
[21/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-air-13-inch-m5-2026-10cpu-10gpu-16gb-1tb -> lấy 0 comment hiển thị / totalCount=0
[22/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-zenbook-s16-um5606ga-ss384ws-ryzen-ai-9-465 -> lấy 0 comment hiển thị / totalCount=0
[23/1000]
Trang 1: +1 comment, tổng 1/1
https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-14-m5-pro-2026-15cpu-16gpu-24gb-1tb -> lấy 1 comment hiển thị / totalCount=1
[24/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-zenbook-14-ux3405ca-st648w-ultra-9-285h -> lấy 0 comment hiển thị / totalCount=0
[25/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-s14-s3407ca-sf923w-ultra-7-255h -> lấy 0 comment hiển thị / totalCount=0
[26/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-16-m5-pro-2026-18cpu-20gpu-24gb-2tb -> lấy 0 comment hiển thị / totalCount=0
[27/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-14-m5-2026-10cpu-10gpu-32gb-2tb-96w -> lấy 0 comment hiển thị / totalCount=0
[28/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-air-15-m5-2026-10cpu-10gpu-24gb-512gb-70w -> lấy 0 comment hiển thị / totalCount=0
[29/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-zenbook-14-um3406ga-qd073ws-ryzen-ai-7-445 -> lấy 0 comment hiển thị / totalCount=0
[30/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-expertbook-p1403cva-c5h16-63ws-core-5-210h -> lấy 0 comment hiển thị / totalCount=0
[31/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-s14-m3407ha-sf490w-r7-260 -> lấy 0 comment hiển thị / totalCount=0
[32/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-16-m5-max-2026-18cpu-32gpu-36gb-2tb -> lấy 0 comment hiển thị / totalCount=0
[33/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-gaming-rog-g16-g614ph-s5101w-r9-8940hx -> lấy 0 comment hiển thị / totalCount=0
[34/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-s14-m3407ha-sf480w-r5-220 -> lấy 0 comment hiển thị / totalCount=0
[35/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-14-m5-2026-10cpu-10gpu-24gb-1tb-nano-96w -> lấy 0 comment hiển thị / totalCount=0
[36/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-s16-m3607ga-sh034w-ryzen-ai-7-445 -> lấy 0 comment hiển thị / totalCount=0
[37/1000]
Trang 1: +6 comment, tổng 6/29
Trang 2: +6 comment, tổng 12/29
Trang 3: +6 comment, tổng 18/29
Trang 4: +6 comment, tổng 24/29
Trang 5: +5 comment, tổng 29/29
https://fptshop.com.vn/may-tinh-xach-tay/macbook-neo-13-inch-8gb-256gb -> lấy 29 comment hiển thị / totalCount=29
[38/1000]
Trang 1: +6 comment, tổng 6/10
Trang 2: +4 comment, tổng 10/10
https://fptshop.com.vn/may-tinh-xach-tay/macbook-neo-13-inch-8gb-512gb -> lấy 10 comment hiển thị / totalCount=10
[39/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/msi-stealth-16-ai-b3wf-007vn-u9-386h -> lấy 0 comment hiển thị / totalCount=0
[40/1000]
Trang 1: +1 comment, tổng 1/1
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-x1607ca-mb980w-ultra-5-225h -> lấy 1 comment hiển thị / totalCount=1
[41/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-14-m5-pro-2026-18cpu-20gpu-24gb-2tb -> lấy 0 comment hiển thị / totalCount=0
[42/1000]
Trang 1: +1 comment, tổng 1/1
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-v15-g5-irl-i5-13420h-83hf00bvvn -> lấy 1 comment hiển thị / totalCount=1
[43/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-zenbook-14-um3406ga-qd075ws-ryzen-ai-7-445 -> lấy 0 comment hiển thị / totalCount=0
[44/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/acer-aspire-lite-15-al15-48p-r5mn-r5-5625u -> lấy 0 comment hiển thị / totalCount=0
[45/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/dell-15-dc15250-i5-1334u-71092479 -> lấy 0 comment hiển thị / totalCount=0
[46/1000]
Trang 1: +6 comment, tổng 6/7
Trang 2: +1 comment, tổng 7/7
https://fptshop.com.vn/may-tinh-xach-tay/acer-gaming-nitro-v-15-anv15-41-r732-r5-6600h -> lấy 7 comment hiển thị / totalCount=7
[47/1000]
Trang 1: +6 comment, tổng 6/16
Trang 2: +6 comment, tổng 12/16
Trang 3: +4 comment, tổng 16/16
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-thinkbook-16-g8-ial-u5-225h-21sk0071vn -> lấy 16 comment hiển thị / totalCount=16
[48/1000]
Trang 1: +6 comment, tổng 6/23
Trang 2: +6 comment, tổng 12/23
Trang 3: +6 comment, tổng 18/23
Trang 4: +5 comment, tổng 23/23
https://fptshop.com.vn/may-tinh-xach-tay/msi-gaming-katana-15-b13udxk-2411vn-i7-13620h -> lấy 23 comment hiển thị / totalCount=23
[49/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/msi-gaming-cyborg-15-a13vek-2089vn-i7-13620h -> lấy 0 comment hiển thị / totalCount=0
[50/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/hp-omnibook-7-14-fs0042tu-core-5-210h-c1mp3pa -> lấy 5 comment hiển thị / totalCount=5
[51/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/colorful-rimbook-l1-i5-13420h-a10205500051 -> lấy 5 comment hiển thị / totalCount=5
[52/1000]
Trang 1: +6 comment, tổng 6/12
Trang 2: +6 comment, tổng 12/12
https://fptshop.com.vn/may-tinh-xach-tay/acer-aspire-lite-16-ai-al16-71p-71wu-ultra-7-155h -> lấy 12 comment hiển thị / totalCount=12
[53/1000]
Trang 1: +6 comment, tổng 6/11
Trang 2: +5 comment, tổng 11/11
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-yoga-slim-7-14ill10-ultra-5-226v-83jx0086vn -> lấy 11 comment hiển thị / totalCount=11
[54/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/hp-omnibook-5-16-ag1066au-ryzen-al-7-350-bz7s9pa -> lấy 5 comment hiển thị / totalCount=5
[55/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/hp-250-g10-i5-1334u-b3wa8at -> lấy 5 comment hiển thị / totalCount=5
[56/1000]
Trang 1: +6 comment, tổng 6/13
Trang 2: +6 comment, tổng 12/13
Trang 3: +1 comment, tổng 13/13
https://fptshop.com.vn/may-tinh-xach-tay/msi-venture-a15-ai-a2hmg-003vn-r7-260 -> lấy 13 comment hiển thị / totalCount=13
[57/1000]
Trang 1: +6 comment, tổng 6/11
Trang 2: +5 comment, tổng 11/11
https://fptshop.com.vn/may-tinh-xach-tay/msi-gaming-katana-15hx-b14wek-027vn-i7-14650hx -> lấy 11 comment hiển thị / totalCount=11
[58/1000]
Trang 1: +6 comment, tổng 6/15
Trang 2: +6 comment, tổng 12/15
Trang 3: +3 comment, tổng 15/15
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-14-a1407ca-ly008ws -> lấy 15 comment hiển thị / totalCount=15
[59/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/acer-nitro-propanel-an16s-61-r193-r9-365 -> lấy 0 comment hiển thị / totalCount=0
[60/1000]
Trang 1: +6 comment, tổng 6/7
Trang 2: +1 comment, tổng 7/7
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-s3407va-ly146w-core-5-210h -> lấy 7 comment hiển thị / totalCount=7
[61/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/colorful-rimbook-s1-i5-12450h-a10205500034 -> lấy 5 comment hiển thị / totalCount=5
[62/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/msi-gaming-stealth-a16-ai-a3xwfg-018vn-ryzen-ai-9-hx-370 -> lấy 0 comment hiển thị / totalCount=0
[63/1000]
Trang 1: +6 comment, tổng 6/11
Trang 2: +5 comment, tổng 11/11
https://fptshop.com.vn/may-tinh-xach-tay/hp-omnibook-5-16-ag1068au-amd-ai-5-340-bz7t0pa -> lấy 11 comment hiển thị / totalCount=11
[64/1000]
Trang 1: +6 comment, tổng 6/18
Trang 2: +6 comment, tổng 12/18
Trang 3: +6 comment, tổng 18/18
https://fptshop.com.vn/may-tinh-xach-tay/colorful-rimbook-l1-i5-12450h-ce50016512c-g-e1ac -> lấy 18 comment hiển thị / totalCount=18
[65/1000]
Trang 1: +6 comment, tổng 6/12
Trang 2: +6 comment, tổng 12/12
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-s14-s3407ca-ly095ws-ultra-5-225h -> lấy 12 comment hiển thị / totalCount=12
[66/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/dell-14-dc14250-core-5-120u-dc4c5386w -> lấy 5 comment hiển thị / totalCount=5
[67/1000]
Trang 1: +6 comment, tổng 6/13
Trang 2: +6 comment, tổng 12/13
Trang 3: +1 comment, tổng 13/13
https://fptshop.com.vn/may-tinh-xach-tay/asus-tuf-gaming-f16-fx608jmr-rv048w-i7-14650hx -> lấy 13 comment hiển thị / totalCount=13
[68/1000]
Trang 1: +6 comment, tổng 6/10
Trang 2: +4 comment, tổng 10/10
https://fptshop.com.vn/may-tinh-xach-tay/msi-modern-15-h-ai-c2hmg-220vn-ultra-7-255h -> lấy 10 comment hiển thị / totalCount=10
[69/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/dell-15-dc15250-i7-1355u-i7u161w11slu -> lấy 5 comment hiển thị / totalCount=5
[70/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-gaming-v16-v3607vu-rp343w-core-5-210h -> lấy 0 comment hiển thị / totalCount=0
[71/1000]
Trang 1: +6 comment, tổng 6/11
Trang 2: +5 comment, tổng 11/11
https://fptshop.com.vn/may-tinh-xach-tay/asus-zenbook-14-oled-ux3405ca-pz187ws -> lấy 11 comment hiển thị / totalCount=11
[72/1000]
Trang 1: +6 comment, tổng 6/7
Trang 2: +1 comment, tổng 7/7
https://fptshop.com.vn/may-tinh-xach-tay/msi-gaming-thin-15-b13uc-3247vn-i5-13420h -> lấy 7 comment hiển thị / totalCount=7
[73/1000]
Trang 1: +6 comment, tổng 6/8
Trang 2: +2 comment, tổng 8/8
https://fptshop.com.vn/may-tinh-xach-tay/acer-aspire-7-gaming-a715-59g-57tu-i5-12450h-16gb -> lấy 8 comment hiển thị / totalCount=8
[74/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/hp-omnibook-5-ai-16-af1046tu-ultra-5-225u-bz7q8pa -> lấy 5 comment hiển thị / totalCount=5
[75/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-yoga-slim-7-14imh9-core-ultra-5-125h-83cv00d8vn -> lấy 5 comment hiển thị / totalCount=5
[76/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/hp-14-em0024au-ryzen-5-7520u-d0bg8pa -> lấy 0 comment hiển thị / totalCount=0
[77/1000]
Trang 1: +6 comment, tổng 6/6
https://fptshop.com.vn/may-tinh-xach-tay/msi-gaming-vector-16-hx-ai-a2xwhg-010vn -> lấy 6 comment hiển thị / totalCount=6
[78/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-gaming-loq-15arp9-r5-7235hs-83jc00lvvn -> lấy 0 comment hiển thị / totalCount=0
[79/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/asus-zenbook-14-ux3405ca-pz188ws-u7-255h -> lấy 5 comment hiển thị / totalCount=5
[80/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/hp-14-ep1176tu-ultra-5-125h-c89zqpa -> lấy 0 comment hiển thị / totalCount=0
[81/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-gaming-legion-5-15irx10-i7-14700hx-83ly004gvn -> lấy 5 comment hiển thị / totalCount=5
[82/1000]
Trang 1: +1 comment, tổng 1/1
https://fptshop.com.vn/may-tinh-xach-tay/acer-aspire-lite-15-al15-42p-r8e6-r5-7430u -> lấy 1 comment hiển thị / totalCount=1
[83/1000]
Trang 1: +6 comment, tổng 6/11
Trang 2: +5 comment, tổng 11/11
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-gaming-loq-15arp10e-r7-7735hs-83s0006rvn -> lấy 11 comment hiển thị / totalCount=11
[84/1000]
Trang 1: +6 comment, tổng 6/28
Trang 2: +6 comment, tổng 12/28
Trang 3: +6 comment, tổng 18/28
Trang 4: +6 comment, tổng 24/28
Trang 5: +4 comment, tổng 28/28
https://fptshop.com.vn/may-tinh-xach-tay/dell-15-dc15255-r5-7530u-dc5r5802w1 -> lấy 28 comment hiển thị / totalCount=28
[85/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/asus-tuf-gaming-f16-fx608jpr-rv044w-i7-14650hx -> lấy 5 comment hiển thị / totalCount=5
[86/1000]
Trang 1: +6 comment, tổng 6/11
Trang 2: +5 comment, tổng 11/11
https://fptshop.com.vn/may-tinh-xach-tay/msi-gaming-katana-15-hx-b14wgk-023vn-i7-14650hx -> lấy 11 comment hiển thị / totalCount=11
[87/1000]
Trang 1: +6 comment, tổng 6/10
Trang 2: +4 comment, tổng 10/10
https://fptshop.com.vn/may-tinh-xach-tay/dell-15-dc15250-i5-1334u-71071928 -> lấy 10 comment hiển thị / totalCount=10
[88/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/dell-14-dc14255-ryzen-ai-5-330-dc4ai5278w1 -> lấy 0 comment hiển thị / totalCount=0
[89/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-thinkpad-x9-15-gen-1-ultra-7-258v-21q60055vn -> lấy 5 comment hiển thị / totalCount=5
[90/1000]
Trang 1: +6 comment, tổng 6/7
Trang 2: +1 comment, tổng 7/7
https://fptshop.com.vn/may-tinh-xach-tay/dell-15-dc15250-i7-1355u-cph997 -> lấy 7 comment hiển thị / totalCount=7
[91/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-thinkbook-16-g8-ial-ultra-7-255h-21sk0073vn -> lấy 0 comment hiển thị / totalCount=0
[92/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/macbook-pro-14-inch-m5-2025-10cpu-10gpu-24gb-1tb-96w -> lấy 0 comment hiển thị / totalCount=0
[93/1000]
Trang 1: +6 comment, tổng 6/25
Trang 2: +6 comment, tổng 12/25
Trang 3: +6 comment, tổng 18/25
Trang 4: +6 comment, tổng 24/25
Trang 5: +1 comment, tổng 25/25
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-ideapad-slim-3-15arp10-r5-7533hs-83k70019vn -> lấy 25 comment hiển thị / totalCount=25
[94/1000]
Trang 1: +6 comment, tổng 6/19
Trang 2: +6 comment, tổng 12/19
Trang 3: +6 comment, tổng 18/19
Trang 4: +1 comment, tổng 19/19
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-gaming-16-k3605vc-rp491w-i7-13620h -> lấy 19 comment hiển thị / totalCount=19
[95/1000]
Trang 1: +1 comment, tổng 1/1
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-thinkbook-14-g9-irl-i5-13420h -> lấy 1 comment hiển thị / totalCount=1
[96/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-m1405naq-ly010w-r5-150 -> lấy 5 comment hiển thị / totalCount=5
[97/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-loq-e-15irx11-i5-13450hx -> lấy 5 comment hiển thị / totalCount=5
[98/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/hp-250r-g10-core-7-150u-cc9c0pt -> lấy 0 comment hiển thị / totalCount=0
[99/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/asus-gaming-rog-flow-z13-gz302eac-ru184ws-ai-max-395 -> lấy 0 comment hiển thị / totalCount=0
[100/1000]
Trang 1: +6 comment, tổng 6/7
Trang 2: +1 comment, tổng 7/7
https://fptshop.com.vn/may-tinh-xach-tay/acer-gaming-nitro-v-15-propanel-anv15-52-72bm-i7-13620h -> lấy 7 comment hiển thị / totalCount=7
[101/1000]
Trang 1: +6 comment, tổng 6/6
https://fptshop.com.vn/may-tinh-xach-tay/hp-omnibook-5-ai-16-af1048tu-ultra-5-225u-bz7q9pa -> lấy 6 comment hiển thị / totalCount=6
[102/1000]
Trang 1: +6 comment, tổng 6/14
Trang 2: +6 comment, tổng 12/14
Trang 3: +2 comment, tổng 14/14
https://fptshop.com.vn/may-tinh-xach-tay/lenovo-ideapad-slim-3-15irh10-83k1000gvn -> lấy 14 comment hiển thị / totalCount=14
[103/1000]
Trang 1: không còn comment nào để thu thập.
https://fptshop.com.vn/may-tinh-xach-tay/acer-gaming-nitro-propanel-an16s-61-r5f4-r7-350 -> lấy 0 comment hiển thị / totalCount=0
[104/1000]
Trang 1: +5 comment, tổng 5/5
https://fptshop.com.vn/may-tinh-xach-tay/dell-16-dc16250-core-5-120u-71076092 -> lấy 5 comment hiển thị / totalCount=5
[105/1000]
Trang 1: +6 comment, tổng 6/11
Trang 2: +5 comment, tổng 11/11
https://fptshop.com.vn/may-tinh-xach-tay/asus-vivobook-15-oled-a1505va-l1688w-i7-13620h -> lấy 11 comment hiển thị / totalCount=11
[106/1000]
Trang 1: không còn comment nào để thu thập.

,review_id,shop_id,item_id,product_url,product_name,brand,price,final_price,rating_count_total,user_id,...,image_review,created_at,like_count,product_items,reply_content,reply_created_at,reply_user_id,reply_is_admin,reply_like_count,source
0,Anh KhoiPD DX_201234,FPTShop,059564510814,https://fptshop.com.vn/may-tinh-xach-tay/color...,Colorful Rimbook L1 i5 13420H (A10205500050),Colorful,14990000,14990000,3,Anh KhoiPD DX,...,None,2026-04-05T07:54:54.114000+00:00,0,,None,None,None,None,None,FPTShop
1,Bình Nguyễn_196901,FPTShop,108185810205,https://fptshop.com.vn/may-tinh-xach-tay/asus-...,Asus Zenbook 14 UX3405CA-ST629W Ultra 7-255H,Asus,34090000,34090000,2,Bình Nguyễn,...,None,2026-03-28T01:12:58.994000+00:00,0,,"Chào anh Bình Dạ, sản phẩm không có màn hình c...",2026-03-28T01:17:57+00:00,Nguyễn Phương Thanh,True,0,FPTShop
2,Bình_210331,FPTShop,320017710671,https://fptshop.com.vn/may-tinh-xach-tay/macbo...,MacBook Air 15 M5 2026 10CPU/10GPU/24GB/1TB,Apple,45990000,45990000,89,Bình,...,None,2026-04-20T14:21:29.756000+00:00,1,,"Chào anh Bình Dạ, cục sạc đi kèm là 35W ạ. Hiệ...",2026-04-20T14:25:41+00:00,Nguyễn Phương Thanh,True,0,FPTShop
3,Thanh_205235,FPTShop,431825326108,https://fptshop.com.vn/may-tinh-xach-tay/macbo...,MacBook Pro 14 M5 Pro 2026 15CPU/16GPU/24GB/1TB,Apple,59990000,59990000,5,Thanh,...,None,2026-04-12T08:04:37.157000+00:00,0,,"Chào anh Thanh, Dạ mẫu này là mẫu M5 Pro thườn...",2026-04-12T08:07:58+00:00,Đông Chí Linh,True,0,FPTShop
4,A Dũng_205578,FPTShop,741367556191,https://fptshop.com.vn/may-tinh-xach-tay/macbo...,MacBook Neo 13 8GB/256GB,Apple,16490000,16490000,24,A Dũng,...,None,2026-04-12T14:04:10.428000+00:00,0,,"Chào anh Dũng, Dạ hiện em kiểm tra thì máy này...",2026-04-12T14:18:43+00:00,Đông Chí Linh,True,0.0,FPTShop

,review_id,shop_id,item_id,product_url,product_name,brand,price,final_price,rating_count_total,user_id,...,image_review,created_at,like_count,product_items,reply_content,reply_created_at,reply_user_id,reply_is_admin,reply_like_count,source
9085,Trung Kiên_43500,FPTShop,760277143745,https://fptshop.com.vn/may-tinh-xach-tay/acer-...,Acer Aspire 3 A315-59-51X8 i5 1235U (NX.K6TSV....,Xiaomi,0,0,6,Trung Kiên,...,None,2024-12-22T02:08:42.290000+00:00,0,,"Chào anh Kiên, Dạ, bên em có hỗ trợ giao hàng ...",2024-12-22T02:14:56+00:00,Nguyễn Thành Đạt,True,0.0,FPTShop
9086,Vũ Hùng Vương_29569,FPTShop,760277143745,https://fptshop.com.vn/may-tinh-xach-tay/acer-...,Acer Aspire 3 A315-59-51X8 i5 1235U (NX.K6TSV....,Xiaomi,0,0,6,Vũ Hùng Vương,...,None,2024-12-13T02:47:46.757000+00:00,0,,NaN,NaN,NaN,None,NaN,FPTShop
9087,Nguyễn Tất Đạt_12577,FPTShop,760277143745,https://fptshop.com.vn/may-tinh-xach-tay/acer-...,Acer Aspire 3 A315-59-51X8 i5 1235U (NX.K6TSV....,Xiaomi,0,0,6,Nguyễn Tất Đạt,...,None,2024-12-03T06:35:31.599000+00:00,0,,Chào anh Đạt Dạ có sẵn hàng nhiều khu vực nhé ...,2024-12-03T06:41:10+00:00,Huỳnh Ngọc Dư,True,0.0,FPTShop
9088,Shushi_4074,FPTShop,760277143745,https://fptshop.com.vn/may-tinh-xach-tay/acer-...,Acer Aspire 3 A315-59-51X8 i5 1235U (NX.K6TSV....,Xiaomi,0,0,6,Shushi,...,None,2024-11-01T00:20:23.767000+00:00,0,,Chào Anh/Chị Shushi Laptop Acer Aspire 3 A315-...,2024-11-01T03:18:38+00:00,Ngô Thị Hồng Ngọc,True,0.0,FPTShop
9089,ân_212163,FPTShop,085911301289,https://fptshop.com.vn/may-tinh-xach-tay/hp-en...,HP ENVY x360 13-bd0528TU i7 1165G7/4Y0Y3PA,Xiaomi,0,0,89,ân,...,None,2026-04-23T15:53:51.158000+00:00,0,,"Chào anh Ân, Dạ sản phẩm này bên em ngừng kinh...",2026-04-24T02:01:01+00:00,Nguyễn Đức Huy,True,0,FPTShop

Tổng số review thu được: 9090

In [14]:
from pathlib import Path

Path("data").mkdir(parents=True, exist_ok=True)
output_path = "data/fptshop_laptop_raw.csv"
df_raw.to_csv(output_path, index=False, encoding="utf-8-sig")
print(f"Đã lưu dữ liệu thô vào: {output_path}")

Đã lưu dữ liệu thô vào: data/fptshop_laptop_raw.csv